In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/abulbasar/data/refs/heads/master/startups.csv")
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11              NaN    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47        NaN       135426.92              NaN  California   42559.73
48     542.05        51743.15              NaN    New York   35673.41
49        NaN       116983.80         45173.06  California   14681.40

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        48 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  47 non-null     float64
 3   State            50 non-null     str
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.5 KB

In [4]:
df.isnull()

    R&D Spend  Administration  Marketing Spend  State  Profit
0       False           False            False  False   False
1       False           False            False  False   False
2       False           False            False  False   False
3       False           False            False  False   False
4       False           False            False  False   False
5       False           False            False  False   False
6       False           False            False  False   False
7       False           False            False  False   False
8       False           False            False  False   False
9       False           False            False  False   False
10      False           False            False  False   False
11      False           False            False  False   False
12      False           False            False  False   False
13      False           False            False  False   False
14      False           False            False  False   False
15      False           False            False  False   False
16      False           False            False  False   False
17      False           False            False  False   False
18      False           False            False  False   False
19      False           False             True  False   False
20      False           False            False  False   False
21      False           False            False  False   False
22      False           False            False  False   False
23      False           False            False  False   False
24      False           False            False  False   False
25      False           False            False  False   False
26      False           False            False  False   False
27      False           False            False  False   False
28      False           False            False  False   False
29      False           False            False  False   False
30      False           False            False  False   False
31      False           False            False  False   False
32      False           False            False  False   False
33      False           False            False  False   False
34      False           False            False  False   False
35      False           False            False  False   False
36      False           False            False  False   False
37      False           False            False  False   False
38      False           False            False  False   False
39      False           False            False  False   False
40      False           False            False  False   False
41      False           False            False  False   False
42      False           False            False  False   False
43      False           False            False  False   False
44      False           False            False  False   False
45      False           False            False  False   False
46      False           False            False  False   False
47       True           False             True  False   False
48      False           False             True  False   False
49       True           False            False  False   False

In [5]:
df.isnull().sum()

R&D Spend          2
Administration     0
Marketing Spend    3
State              0
Profit             0
dtype: int64

In [6]:
df.isnull().sum().sum()

np.int64(5)

In [7]:
import numpy as np

In [8]:
np.prod(df.shape)

np.int64(250)

In [9]:
df.isnull().sum().sum() / np.prod(df.shape)

np.float64(0.02)

In [12]:
a = df.isna().sum(axis = 1)
df[a>0]

    R&D Spend  Administration  Marketing Spend       State     Profit
19   86419.70       153514.11              NaN    New York  122776.86
47        NaN       135426.92              NaN  California   42559.73
48     542.05        51743.15              NaN    New York   35673.41
49        NaN       116983.80         45173.06  California   14681.40

In [13]:
df.dropna()

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75

In [14]:
df.dropna(axis = 1)

    Administration       State     Profit
0        136897.80    New York  192261.83
1        151377.59  California  191792.06
2        101145.55     Florida  191050.39
3        118671.85    New York  182901.99
4         91391.77     Florida  166187.94
5         99814.71    New York  156991.12
6        147198.87  California  156122.51
7        145530.06     Florida  155752.60
8        148718.95    New York  152211.77
9        108679.17  California  149759.96
10       110594.11     Florida  146121.95
11        91790.61  California  144259.40
12       127320.38     Florida  141585.52
13       135495.07  California  134307.35
14       156547.42     Florida  132602.65
15       122616.84    New York  129917.04
16       121597.55  California  126992.93
17       145077.58    New York  125370.37
18       114175.79     Florida  124266.90
19       153514.11    New York  122776.86
20       113867.30  California  118474.03
21       153773.43    New York  111313.02
22       122782.75     Florida  110352.25
23       105751.03     Florida  108733.99
24        99281.34    New York  108552.04
25       139553.16  California  107404.34
26       144135.98     Florida  105733.54
27       127864.55    New York  105008.31
28       182645.56     Florida  103282.38
29       153032.06    New York  101004.64
30       115641.28     Florida   99937.59
31       152701.92    New York   97483.56
32       129219.61  California   97427.84
33       103057.49     Florida   96778.92
34       157693.92  California   96712.80
35        85047.44    New York   96479.51
36       127056.21     Florida   90708.19
37        51283.14  California   89949.14
38        65947.93    New York   81229.06
39        82982.09  California   81005.76
40       118546.05  California   78239.91
41        84710.77     Florida   77798.83
42        96189.63  California   71498.49
43       127382.30    New York   69758.98
44       154806.14  California   65200.33
45       124153.04    New York   64926.08
46       115816.21     Florida   49490.75
47       135426.92  California   42559.73
48        51743.15    New York   35673.41
49       116983.80  California   14681.40

In [15]:
df.fillna(0.0)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [19]:
df.mean(numeric_only=True)

R&D Spend           76793.349583
Administration     121344.639600
Marketing Spend    224494.784894
Profit             112012.639200
dtype: float64

In [20]:
df.fillna(df.mean(numeric_only=True))

        R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.200000       136897.80    471784.100000    New York  192261.83
1   162597.700000       151377.59    443898.530000  California  191792.06
2   153441.510000       101145.55    407934.540000     Florida  191050.39
3   144372.410000       118671.85    383199.620000    New York  182901.99
4   142107.340000        91391.77    366168.420000     Florida  166187.94
5   131876.900000        99814.71    362861.360000    New York  156991.12
6   134615.460000       147198.87    127716.820000  California  156122.51
7   130298.130000       145530.06    323876.680000     Florida  155752.60
8   120542.520000       148718.95    311613.290000    New York  152211.77
9   123334.880000       108679.17    304981.620000  California  149759.96
10  101913.080000       110594.11    229160.950000     Florida  146121.95
11  100671.960000        91790.61    249744.550000  California  144259.40
12   93863.750000       127320.38    249839.440000     Florida  141585.52
13   91992.390000       135495.07    252664.930000  California  134307.35
14  119943.240000       156547.42    256512.920000     Florida  132602.65
15  114523.610000       122616.84    261776.230000    New York  129917.04
16   78013.110000       121597.55    264346.060000  California  126992.93
17   94657.160000       145077.58    282574.310000    New York  125370.37
18   91749.160000       114175.79    294919.570000     Florida  124266.90
19   86419.700000       153514.11    224494.784894    New York  122776.86
20   76253.860000       113867.30    298664.470000  California  118474.03
21   78389.470000       153773.43    299737.290000    New York  111313.02
22   73994.560000       122782.75    303319.260000     Florida  110352.25
23   67532.530000       105751.03    304768.730000     Florida  108733.99
24   77044.010000        99281.34    140574.810000    New York  108552.04
25   64664.710000       139553.16    137962.620000  California  107404.34
26   75328.870000       144135.98    134050.070000     Florida  105733.54
27   72107.600000       127864.55    353183.810000    New York  105008.31
28   66051.520000       182645.56    118148.200000     Florida  103282.38
29   65605.480000       153032.06    107138.380000    New York  101004.64
30   61994.480000       115641.28     91131.240000     Florida   99937.59
31   61136.380000       152701.92     88218.230000    New York   97483.56
32   63408.860000       129219.61     46085.250000  California   97427.84
33   55493.950000       103057.49    214634.810000     Florida   96778.92
34   46426.070000       157693.92    210797.670000  California   96712.80
35   46014.020000        85047.44    205517.640000    New York   96479.51
36   28663.760000       127056.21    201126.820000     Florida   90708.19
37   44069.950000        51283.14    197029.420000  California   89949.14
38   20229.590000        65947.93    185265.100000    New York   81229.06
39   38558.510000        82982.09    174999.300000  California   81005.76
40   28754.330000       118546.05    172795.670000  California   78239.91
41   27892.920000        84710.77    164470.710000     Florida   77798.83
42   23640.930000        96189.63    148001.110000  California   71498.49
43   15505.730000       127382.30     35534.170000    New York   69758.98
44   22177.740000       154806.14     28334.720000  California   65200.33
45    1000.230000       124153.04      1903.930000    New York   64926.08
46    1315.460000       115816.21    297114.460000     Florida   49490.75
47   76793.349583       135426.92    224494.784894  California   42559.73
48     542.050000        51743.15    224494.784894    New York   35673.41
49   76793.349583       116983.80     45173.060000  California   14681.40

In [27]:
def iqr(a):
    q1, q3 = np.percentile(a, [25, 75])
    return q3-q1

In [28]:
a = [6, 10, 8, 11, 13, 15, 6]
np.mean(a), np.median(a), np.max(a)-np.min(a), iqr(a)

(np.float64(9.857142857142858), np.float64(10.0), np.int64(9), np.float64(5.0))

In [29]:
a = [6, 10, 8, 11, 13, 15, 6, 100]
np.mean(a), np.median(a), np.max(a)-np.min(a), iqr(a)

(np.float64(21.125), np.float64(10.5), np.int64(94), np.float64(6.0))

In [30]:
# median is less impacted by the outliers/extreme values
# hence, median is considered a "robust" statistic
# iqr is robust statistic to measure dispersion .. while range, std, var are not.

In [32]:
df.median(numeric_only=True)

R&D Spend           74661.715
Administration     122699.795
Marketing Spend    229160.950
Profit             107978.190
dtype: float64

In [31]:
df.fillna(df.median(numeric_only=True))

     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.200       136897.80        471784.10    New York  192261.83
1   162597.700       151377.59        443898.53  California  191792.06
2   153441.510       101145.55        407934.54     Florida  191050.39
3   144372.410       118671.85        383199.62    New York  182901.99
4   142107.340        91391.77        366168.42     Florida  166187.94
5   131876.900        99814.71        362861.36    New York  156991.12
6   134615.460       147198.87        127716.82  California  156122.51
7   130298.130       145530.06        323876.68     Florida  155752.60
8   120542.520       148718.95        311613.29    New York  152211.77
9   123334.880       108679.17        304981.62  California  149759.96
10  101913.080       110594.11        229160.95     Florida  146121.95
11  100671.960        91790.61        249744.55  California  144259.40
12   93863.750       127320.38        249839.44     Florida  141585.52
13   91992.390       135495.07        252664.93  California  134307.35
14  119943.240       156547.42        256512.92     Florida  132602.65
15  114523.610       122616.84        261776.23    New York  129917.04
16   78013.110       121597.55        264346.06  California  126992.93
17   94657.160       145077.58        282574.31    New York  125370.37
18   91749.160       114175.79        294919.57     Florida  124266.90
19   86419.700       153514.11        229160.95    New York  122776.86
20   76253.860       113867.30        298664.47  California  118474.03
21   78389.470       153773.43        299737.29    New York  111313.02
22   73994.560       122782.75        303319.26     Florida  110352.25
23   67532.530       105751.03        304768.73     Florida  108733.99
24   77044.010        99281.34        140574.81    New York  108552.04
25   64664.710       139553.16        137962.62  California  107404.34
26   75328.870       144135.98        134050.07     Florida  105733.54
27   72107.600       127864.55        353183.81    New York  105008.31
28   66051.520       182645.56        118148.20     Florida  103282.38
29   65605.480       153032.06        107138.38    New York  101004.64
30   61994.480       115641.28         91131.24     Florida   99937.59
31   61136.380       152701.92         88218.23    New York   97483.56
32   63408.860       129219.61         46085.25  California   97427.84
33   55493.950       103057.49        214634.81     Florida   96778.92
34   46426.070       157693.92        210797.67  California   96712.80
35   46014.020        85047.44        205517.64    New York   96479.51
36   28663.760       127056.21        201126.82     Florida   90708.19
37   44069.950        51283.14        197029.42  California   89949.14
38   20229.590        65947.93        185265.10    New York   81229.06
39   38558.510        82982.09        174999.30  California   81005.76
40   28754.330       118546.05        172795.67  California   78239.91
41   27892.920        84710.77        164470.71     Florida   77798.83
42   23640.930        96189.63        148001.11  California   71498.49
43   15505.730       127382.30         35534.17    New York   69758.98
44   22177.740       154806.14         28334.72  California   65200.33
45    1000.230       124153.04          1903.93    New York   64926.08
46    1315.460       115816.21        297114.46     Florida   49490.75
47   74661.715       135426.92        229160.95  California   42559.73
48     542.050        51743.15        229160.95    New York   35673.41
49   74661.715       116983.80         45173.06  California   14681.40

In [33]:
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11              NaN    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47        NaN       135426.92              NaN  California   42559.73
48     542.05        51743.15              NaN    New York   35673.41
49        NaN       116983.80         45173.06  California   14681.40

In [49]:
a = df[df.State == 'California']
a.median(numeric_only = True)

R&D Spend           64664.71
Administration     121597.55
Marketing Spend    186014.36
Profit              97427.84
dtype: float64

In [50]:
a = df[df.State == 'New York']
a.median(numeric_only = True)

R&D Spend           77044.01
Administration     127382.30
Marketing Spend    261776.23
Profit             108552.04
dtype: float64

In [52]:
frames = []
for state in df.State.unique():
    print(state)
    a = df[df.State == state]
    a = a.fillna(a.median(numeric_only=True))
    frames.append(a)
df = pd.concat(frames)
df.sort_index()

New York
California
Florida

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11        261776.23    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47   64664.71       135426.92        186014.36  California   42559.73
48     542.05        51743.15        261776.23    New York   35673.41
49   64664.71       116983.80         45173.06  California   14681.40

In [53]:
df = pd.read_csv("/home/aio/training/data/stocks.csv")
df

,date,open,high,low,close,volume,adjclose,symbol
0,2000-07-17,95.437500,97.500000,92.750000,96.625000,3508100.0,74.269199,XLNX
1,2000-07-17,22.625000,22.750000,22.437500,22.562500,201600.0,13.486140,ES
2,2000-07-17,6.750002,6.937503,6.375000,6.500000,1235700.0,5.241649,CHK
3,2000-07-17,19.812501,20.187500,19.500001,20.187500,1434100.0,3.806147,NI
4,2000-07-17,30.500000,30.687500,30.000000,30.031250,254600.0,19.811830,SNA
...,...,...,...,...,...,...,...,...
1857087,2016-08-15,79.540001,80.150002,78.949997,79.750000,1378500.0,79.750000,MNK
1857088,2016-08-15,27.180000,27.350000,27.139999,27.230000,3225500.0,27.230000,HBI
1857089,2016-08-15,60.779999,61.270000,60.529999,61.209999,2375600.0,61.209999,MCHP
1857090,2016-08-15,66.440002,67.000000,66.320000,66.540001,1284100.0,66.540001,EQR
1857091,2016-08-15,36.430000,36.650002,36.049999,36.070000,3112500.0,36.070000,SE

In [54]:
stocks = df.copy()
stocks.index = pd.to_datetime(stocks.date)
stocks

,date,open,high,low,close,volume,adjclose,symbol
date,,,,,,,,
2000-07-17,2000-07-17,95.437500,97.500000,92.750000,96.625000,3508100.0,74.269199,XLNX
2000-07-17,2000-07-17,22.625000,22.750000,22.437500,22.562500,201600.0,13.486140,ES
2000-07-17,2000-07-17,6.750002,6.937503,6.375000,6.500000,1235700.0,5.241649,CHK
2000-07-17,2000-07-17,19.812501,20.187500,19.500001,20.187500,1434100.0,3.806147,NI
2000-07-17,2000-07-17,30.500000,30.687500,30.000000,30.031250,254600.0,19.811830,SNA
...,...,...,...,...,...,...,...,...
2016-08-15,2016-08-15,79.540001,80.150002,78.949997,79.750000,1378500.0,79.750000,MNK
2016-08-15,2016-08-15,27.180000,27.350000,27.139999,27.230000,3225500.0,27.230000,HBI
2016-08-15,2016-08-15,60.779999,61.270000,60.529999,61.209999,2375600.0,61.209999,MCHP
2016-08-15,2016-08-15,66.440002,67.000000,66.320000,66.540001,1284100.0,66.540001,EQR
2016-08-15,2016-08-15,36.430000,36.650002,36.049999,36.070000,3112500.0,36.070000,SE

In [57]:
csco = stocks[stocks.symbol == 'CSCO']
csco.adjclose[:20]

date
2000-07-17    60.073658
2000-07-18    58.024467
2000-07-19    57.646984
2000-07-20    59.965806
2000-07-21    58.779432
2000-07-24    56.999871
2000-07-25    58.779432
2000-07-26    59.156914
2000-07-27    58.671580
2000-07-28    54.195715
2000-07-31    56.460610
2000-08-01    54.519271
2000-08-02    52.577932
2000-08-03    55.543867
2000-08-04    56.568462
2000-08-07    57.161649
2000-08-08    56.514536
2000-08-09    58.509801
2000-08-10    54.681049
2000-08-11    55.489941
Name: adjclose, dtype: float64

In [58]:
stocks.index

DatetimeIndex(['2000-07-17', '2000-07-17', '2000-07-17', '2000-07-17',
               '2000-07-17', '2000-07-17', '2000-07-17', '2000-07-17',
               '2000-07-17', '2000-07-17',
               ...
               '2016-08-15', '2016-08-15', '2016-08-15', '2016-08-15',
               '2016-08-15', '2016-08-15', '2016-08-15', '2016-08-15',
               '2016-08-15', '2016-08-15'],
              dtype='datetime64[us]', name='date', length=1857092, freq=None)

In [61]:
csco = stocks[stocks.symbol == 'CSCO']
csco
#csco = stocks.asfreq("D")
#csco.adjclose[:20]

,date,open,high,low,close,volume,adjclose,symbol
date,,,,,,,,
2000-07-17,2000-07-17,67.625000,69.750000,67.375000,69.625000,41995400.0,60.073658,CSCO
2000-07-18,2000-07-18,68.250000,69.125000,67.062500,67.250000,29673200.0,58.024467,CSCO
2000-07-19,2000-07-19,67.125000,67.937500,66.250000,66.812500,24010200.0,57.646984,CSCO
2000-07-20,2000-07-20,67.250000,69.750000,67.187500,69.500000,43828700.0,59.965806,CSCO
2000-07-21,2000-07-21,68.625000,69.625000,67.734383,68.125000,29126500.0,58.779432,CSCO
...,...,...,...,...,...,...,...,...
2016-08-09,2016-08-09,31.110001,31.250000,30.840000,30.940001,19159500.0,30.940001,CSCO
2016-08-10,2016-08-10,31.010000,31.129999,30.740000,30.850000,16684300.0,30.850000,CSCO
2016-08-11,2016-08-11,30.950001,31.020000,30.860001,30.950001,24020900.0,30.950001,CSCO
2016-08-12,2016-08-12,30.920000,30.990000,30.799999,30.870001,13430600.0,30.870001,CSCO
2016-08-15,2016-08-15,30.980000,31.240000,30.889999,31.190001,21796800.0,31.190001,CSCO

In [63]:
csco[csco.index.duplicated()]

Empty DataFrame
Columns: [date, open, high, low, close, volume, adjclose, symbol]
Index: []

In [69]:
csco = stocks[stocks.symbol == 'CSCO'].adjclose
csco = csco.asfreq("D")
csco[:20]

date
2000-07-17    60.073658
2000-07-18    58.024467
2000-07-19    57.646984
2000-07-20    59.965806
2000-07-21    58.779432
2000-07-22          NaN
2000-07-23          NaN
2000-07-24    56.999871
2000-07-25    58.779432
2000-07-26    59.156914
2000-07-27    58.671580
2000-07-28    54.195715
2000-07-29          NaN
2000-07-30          NaN
2000-07-31    56.460610
2000-08-01    54.519271
2000-08-02    52.577932
2000-08-03    55.543867
2000-08-04    56.568462
2000-08-05          NaN
Freq: D, Name: adjclose, dtype: float64

In [70]:
csco = stocks[stocks.symbol == 'CSCO'].adjclose
csco = csco.asfreq("B")
csco[:20]

date
2000-07-17    60.073658
2000-07-18    58.024467
2000-07-19    57.646984
2000-07-20    59.965806
2000-07-21    58.779432
2000-07-24    56.999871
2000-07-25    58.779432
2000-07-26    59.156914
2000-07-27    58.671580
2000-07-28    54.195715
2000-07-31    56.460610
2000-08-01    54.519271
2000-08-02    52.577932
2000-08-03    55.543867
2000-08-04    56.568462
2000-08-07    57.161649
2000-08-08    56.514536
2000-08-09    58.509801
2000-08-10    54.681049
2000-08-11    55.489941
Freq: B, Name: adjclose, dtype: float64

In [74]:
a = csco[(csco.index>'2000-12') & (csco.index<'2000-12-31')][:20]
a

date
2000-12-04    39.527820
2000-12-05    44.974354
2000-12-06    44.381167
2000-12-07    43.086941
2000-12-08    45.190059
2000-12-11    47.293176
2000-12-12    46.915693
2000-12-13    44.111537
2000-12-14    43.949759
2000-12-15    41.563533
2000-12-18    37.047220
2000-12-19    36.022624
2000-12-20    31.492833
2000-12-21    33.542024
2000-12-22    35.806920
2000-12-25          NaN
2000-12-26    35.159807
2000-12-27    35.159807
2000-12-28    34.135211
2000-12-29    33.002764
Freq: B, Name: adjclose, dtype: float64

In [75]:
a.ffill()

date
2000-12-04    39.527820
2000-12-05    44.974354
2000-12-06    44.381167
2000-12-07    43.086941
2000-12-08    45.190059
2000-12-11    47.293176
2000-12-12    46.915693
2000-12-13    44.111537
2000-12-14    43.949759
2000-12-15    41.563533
2000-12-18    37.047220
2000-12-19    36.022624
2000-12-20    31.492833
2000-12-21    33.542024
2000-12-22    35.806920
2000-12-25    35.806920
2000-12-26    35.159807
2000-12-27    35.159807
2000-12-28    34.135211
2000-12-29    33.002764
Freq: B, Name: adjclose, dtype: float64

In [76]:
a.bfill()

date
2000-12-04    39.527820
2000-12-05    44.974354
2000-12-06    44.381167
2000-12-07    43.086941
2000-12-08    45.190059
2000-12-11    47.293176
2000-12-12    46.915693
2000-12-13    44.111537
2000-12-14    43.949759
2000-12-15    41.563533
2000-12-18    37.047220
2000-12-19    36.022624
2000-12-20    31.492833
2000-12-21    33.542024
2000-12-22    35.806920
2000-12-25    35.159807
2000-12-26    35.159807
2000-12-27    35.159807
2000-12-28    34.135211
2000-12-29    33.002764
Freq: B, Name: adjclose, dtype: float64