In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/aio/training/data/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [6]:
df.tail()

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [19]:
df.sample(n = 10)

       carat        cut color clarity  depth  table  price     x     y     z
12116   0.90  Very Good     F     VS1   61.5   55.0   5167  6.25  6.28  3.85
22456   1.50    Premium     I    VVS2   60.2   58.0  10483  7.50  7.34  4.47
53145   0.75    Premium     G     SI1   59.1   59.0   2622  5.98  5.90  3.51
22272   1.10  Very Good     F    VVS1   62.2   59.0  10329  6.56  6.69  4.12
11022   1.24      Ideal     G     SI1   62.7   56.0   4916  6.89  6.85  4.31
48869   0.78       Good     J     SI1   58.0   62.0   2035  6.01  6.05  3.50
25716   1.58      Ideal     G     VS1   61.3   57.0  14624  7.48  7.54  4.60
31718   0.38       Good     G     VS2   58.8   62.0    771  4.68  4.71  2.76
8522    1.04       Good     F     SI2   63.1   60.0   4427  6.35  6.42  4.03
49347   0.71    Premium     E     SI2   60.4   61.0   2096  5.79  5.77  3.49

In [20]:
df.sample(frac=0.1)

       carat        cut color clarity  depth  table  price     x     y     z
44065   0.54       Good     D     SI1   63.2   55.0   1551  5.17  5.21  3.28
17147   1.01    Premium     G    VVS2   61.4   58.0   6843  6.46  6.51  3.98
45145   0.50      Ideal     F     VS2   62.9   55.0   1654  5.10  5.07  3.20
14090   1.35    Premium     I     SI2   59.8   59.0   5715  7.26  7.20  4.32
50535   0.50  Very Good     E    VVS2   62.4   55.0   2275  5.08  5.11  3.18
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
15860   1.10      Ideal     H     VS2   62.7   56.0   6344  6.58  6.63  4.14
38829   0.43    Premium     E     VS2   61.6   59.0   1048  4.84  4.81  2.97
10317   1.03    Premium     D     SI2   61.3   61.0   4764  6.49  6.46  3.97
12094   1.09      Ideal     D     SI2   62.1   56.0   5164  6.56  6.59  4.08
27225   2.14  Very Good     F     SI2   58.2   61.0  17582  8.45  8.50  4.93

[5394 rows x 10 columns]

In [21]:
df.shape

(53940, 10)

In [22]:
len(df)

53940

In [23]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [25]:
pd.__version__

'3.0.5'

In [26]:
df.iloc

In [27]:
df.iloc[100:110]

     carat        cut color clarity  depth  table  price     x     y     z
100   0.75  Very Good     D     SI1   63.2   56.0   2760  5.80  5.75  3.65
101   0.75    Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
102   0.74      Ideal     G     SI1   61.6   55.0   2760  5.80  5.85  3.59
103   0.75    Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
104   0.80      Ideal     I     VS1   62.9   56.0   2760  5.94  5.87  3.72
105   0.75      Ideal     G     SI1   62.2   55.0   2760  5.87  5.80  3.63
106   0.80    Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
107   0.74      Ideal     I    VVS2   62.3   55.0   2761  5.77  5.81  3.61
108   0.81      Ideal     F     SI2   58.8   57.0   2761  6.14  6.11  3.60
109   0.59      Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35

In [28]:
df.iloc[-100:]

       carat        cut color clarity  depth  table  price     x     y     z
53840   0.71       Good     H    VVS2   60.4   63.0   2738  5.69  5.74  3.45
53841   0.80  Very Good     H     SI1   63.8   56.0   2739  5.85  5.91  3.75
53842   0.71      Ideal     H    VVS1   62.0   57.0   2739  5.71  5.75  3.55
53843   0.57      Ideal     E    VVS1   61.8   56.0   2739  5.33  5.35  3.30
53844   0.74  Very Good     D     SI2   61.5   59.0   2740  5.79  5.82  3.57
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[100 rows x 10 columns]

In [29]:
df[["carat", "cut", "color"]]

       carat        cut color
0       0.23      Ideal     E
1       0.21    Premium     E
2       0.23       Good     E
3       0.29    Premium     I
4       0.31       Good     J
...      ...        ...   ...
53935   0.72      Ideal     D
53936   0.72       Good     D
53937   0.70  Very Good     D
53938   0.86    Premium     H
53939   0.75      Ideal     D

[53940 rows x 3 columns]

In [30]:
# https://rpubs.com/Davo2812/1102821

In [31]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [32]:
df[df.cut == 'Premium']

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [33]:
df[df['cut'] == 'Premium']

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [34]:
df[(df['cut'] == 'Premium') & (df.price>2000)]

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [36]:
df.sort_values("cut")

       carat        cut color clarity  depth  table  price     x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
91      0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
97      0.96       Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
123     0.70       Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
124     0.70       Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53921   0.70  Very Good     E     VS2   62.8   60.0   2755  5.59  5.65  3.53
53922   0.70  Very Good     D     VS1   63.1   59.0   2755  5.67  5.58  3.55
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[53940 rows x 10 columns]

In [37]:
df.sort_values("cut", ascending=False)

       carat        cut color clarity  depth  table  price     x     y     z
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9       0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
19      0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53757   0.72       Fair     F     VS2   55.4   64.0   2724  6.06  5.97  3.34
53800   0.90       Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00       Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04       Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71       Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[53940 rows x 10 columns]

In [38]:
df.sort_values(["cut", "price"])

       carat        cut color clarity  depth  table  price     x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
28270   0.25       Fair     E     VS1   55.2   64.0    361  4.21  4.23  2.33
31611   0.23       Fair     G    VVS2   61.4   66.0    369  3.87  3.91  2.39
31615   0.27       Fair     E     VS1   66.4   58.0    371  3.99  4.02  2.66
10030   0.30       Fair     J     VS2   64.8   58.0    416  4.24  4.16  2.72
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
27729   2.00  Very Good     F     SI1   57.9   60.0  18759  8.28  8.34  4.81
27733   1.51  Very Good     F    VVS1   62.6   59.0  18777  7.33  7.24  4.56
27736   2.03  Very Good     H     SI1   63.0   60.0  18781  8.00  7.93  5.02
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04

[53940 rows x 10 columns]

In [39]:
df.sort_values(["cut", "price"], ascending=[True, False])

       carat        cut color clarity  depth  table  price      x      y     z
27646   2.01       Fair     G     SI1   70.6   64.0  18574   7.43   6.64  4.69
27643   2.02       Fair     H     VS2   64.5   57.0  18565   8.00   7.95  5.14
27630   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27623   2.00       Fair     G     VS2   67.6   58.0  18515   7.65   7.61  5.16
27543   2.51       Fair     H     SI2   64.7   57.0  18308   8.44   8.50  5.48
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
19      0.30  Very Good     J     SI1   62.7   59.0    351   4.21   4.27  2.66
9       0.23  Very Good     H     VS1   59.4   61.0    338   4.00   4.05  2.39
7       0.26  Very Good     H     SI1   61.9   55.0    337   4.07   4.11  2.53
5       0.24  Very Good     J    VVS2   62.8   57.0    336   3.94   3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336   3.95   3.98  2.47

[53940 rows x 10 columns]

In [40]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [42]:
list(df.cut.unique())

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']

In [43]:
df.cut.nunique()

5

In [44]:
df.shape

(53940, 10)

In [45]:
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [47]:
df.groupby(["cut", "color"])["price"].count()

cut        color
Fair       D         163
           E         224
           F         312
           G         314
           H         303
           I         175
           J         119
Good       D         662
           E         933
           F         909
           G         871
           H         702
           I         522
           J         307
Ideal      D        2834
           E        3903
           F        3826
           G        4884
           H        3115
           I        2093
           J         896
Premium    D        1603
           E        2337
           F        2331
           G        2924
           H        2360
           I        1428
           J         808
Very Good  D        1513
           E        2400
           F        2164
           G        2299
           H        1824
           I        1204
           J         678
Name: price, dtype: int64

In [48]:
df.groupby("cut").price.mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [49]:
df.groupby("cut").price.agg(["min", "max", "mean"])

           min    max         mean
cut
Fair       337  18574  4358.757764
Good       327  18788  3928.864452
Ideal      326  18806  3457.541970
Premium    326  18823  4584.257704
Very Good  336  18818  3981.759891

In [50]:
df.groupby("cut")[["carat", "price"]].agg(["min", "max", "mean"])

          carat                 price
            min   max      mean   min    max         mean
cut
Fair       0.22  5.01  1.046137   337  18574  4358.757764
Good       0.23  3.01  0.849185   327  18788  3928.864452
Ideal      0.20  3.50  0.702837   326  18806  3457.541970
Premium    0.20  4.01  0.891955   326  18823  4584.257704
Very Good  0.20  4.00  0.806381   336  18818  3981.759891

In [53]:
df.groupby("cut").agg({"price": ["min", "max"], "carat": ["median", "mean"]})

          price         carat
            min    max median      mean
cut
Fair        337  18574   1.00  1.046137
Good        327  18788   0.82  0.849185
Ideal       326  18806   0.54  0.702837
Premium     326  18823   0.86  0.891955
Very Good   336  18818   0.71  0.806381

In [56]:
df.pivot_table(index="cut", columns="color", values="price",aggfunc="mean")

color,D,E,F,G,H,I,J
cut,,,,,,,
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274

In [57]:
df.pivot_table(index="cut", columns="color", values="price",aggfunc="count")

color         D     E     F     G     H     I    J
cut
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678