In [1]:
import pandas as pd

In [58]:
df = pd.read_csv("/home/aio/training/data/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [6]:
df.tail()

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [19]:
df.sample(n = 10)

       carat        cut color clarity  depth  table  price     x     y     z
12116   0.90  Very Good     F     VS1   61.5   55.0   5167  6.25  6.28  3.85
22456   1.50    Premium     I    VVS2   60.2   58.0  10483  7.50  7.34  4.47
53145   0.75    Premium     G     SI1   59.1   59.0   2622  5.98  5.90  3.51
22272   1.10  Very Good     F    VVS1   62.2   59.0  10329  6.56  6.69  4.12
11022   1.24      Ideal     G     SI1   62.7   56.0   4916  6.89  6.85  4.31
48869   0.78       Good     J     SI1   58.0   62.0   2035  6.01  6.05  3.50
25716   1.58      Ideal     G     VS1   61.3   57.0  14624  7.48  7.54  4.60
31718   0.38       Good     G     VS2   58.8   62.0    771  4.68  4.71  2.76
8522    1.04       Good     F     SI2   63.1   60.0   4427  6.35  6.42  4.03
49347   0.71    Premium     E     SI2   60.4   61.0   2096  5.79  5.77  3.49

In [20]:
df.sample(frac=0.1)

       carat        cut color clarity  depth  table  price     x     y     z
44065   0.54       Good     D     SI1   63.2   55.0   1551  5.17  5.21  3.28
17147   1.01    Premium     G    VVS2   61.4   58.0   6843  6.46  6.51  3.98
45145   0.50      Ideal     F     VS2   62.9   55.0   1654  5.10  5.07  3.20
14090   1.35    Premium     I     SI2   59.8   59.0   5715  7.26  7.20  4.32
50535   0.50  Very Good     E    VVS2   62.4   55.0   2275  5.08  5.11  3.18
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
15860   1.10      Ideal     H     VS2   62.7   56.0   6344  6.58  6.63  4.14
38829   0.43    Premium     E     VS2   61.6   59.0   1048  4.84  4.81  2.97
10317   1.03    Premium     D     SI2   61.3   61.0   4764  6.49  6.46  3.97
12094   1.09      Ideal     D     SI2   62.1   56.0   5164  6.56  6.59  4.08
27225   2.14  Very Good     F     SI2   58.2   61.0  17582  8.45  8.50  4.93

[5394 rows x 10 columns]

In [21]:
df.shape

(53940, 10)

In [22]:
len(df)

53940

In [23]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [25]:
pd.__version__

'3.0.5'

In [26]:
df.iloc

In [27]:
df.iloc[100:110]

     carat        cut color clarity  depth  table  price     x     y     z
100   0.75  Very Good     D     SI1   63.2   56.0   2760  5.80  5.75  3.65
101   0.75    Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
102   0.74      Ideal     G     SI1   61.6   55.0   2760  5.80  5.85  3.59
103   0.75    Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
104   0.80      Ideal     I     VS1   62.9   56.0   2760  5.94  5.87  3.72
105   0.75      Ideal     G     SI1   62.2   55.0   2760  5.87  5.80  3.63
106   0.80    Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
107   0.74      Ideal     I    VVS2   62.3   55.0   2761  5.77  5.81  3.61
108   0.81      Ideal     F     SI2   58.8   57.0   2761  6.14  6.11  3.60
109   0.59      Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35

In [28]:
df.iloc[-100:]

       carat        cut color clarity  depth  table  price     x     y     z
53840   0.71       Good     H    VVS2   60.4   63.0   2738  5.69  5.74  3.45
53841   0.80  Very Good     H     SI1   63.8   56.0   2739  5.85  5.91  3.75
53842   0.71      Ideal     H    VVS1   62.0   57.0   2739  5.71  5.75  3.55
53843   0.57      Ideal     E    VVS1   61.8   56.0   2739  5.33  5.35  3.30
53844   0.74  Very Good     D     SI2   61.5   59.0   2740  5.79  5.82  3.57
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[100 rows x 10 columns]

In [29]:
df[["carat", "cut", "color"]]

       carat        cut color
0       0.23      Ideal     E
1       0.21    Premium     E
2       0.23       Good     E
3       0.29    Premium     I
4       0.31       Good     J
...      ...        ...   ...
53935   0.72      Ideal     D
53936   0.72       Good     D
53937   0.70  Very Good     D
53938   0.86    Premium     H
53939   0.75      Ideal     D

[53940 rows x 3 columns]

In [30]:
# https://rpubs.com/Davo2812/1102821

In [31]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [32]:
df[df.cut == 'Premium']

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [33]:
df[df['cut'] == 'Premium']

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [59]:
df[(df['cut'] == 'Premium') & (df.price>2000)]

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [61]:
df.query("cut == 'Premium' and price > 2000")

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [36]:
df.sort_values("cut")

       carat        cut color clarity  depth  table  price     x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
91      0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
97      0.96       Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
123     0.70       Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
124     0.70       Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53921   0.70  Very Good     E     VS2   62.8   60.0   2755  5.59  5.65  3.53
53922   0.70  Very Good     D     VS1   63.1   59.0   2755  5.67  5.58  3.55
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[53940 rows x 10 columns]

In [37]:
df.sort_values("cut", ascending=False)

       carat        cut color clarity  depth  table  price     x     y     z
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9       0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
19      0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53757   0.72       Fair     F     VS2   55.4   64.0   2724  6.06  5.97  3.34
53800   0.90       Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00       Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04       Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71       Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[53940 rows x 10 columns]

In [38]:
df.sort_values(["cut", "price"])

       carat        cut color clarity  depth  table  price     x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
28270   0.25       Fair     E     VS1   55.2   64.0    361  4.21  4.23  2.33
31611   0.23       Fair     G    VVS2   61.4   66.0    369  3.87  3.91  2.39
31615   0.27       Fair     E     VS1   66.4   58.0    371  3.99  4.02  2.66
10030   0.30       Fair     J     VS2   64.8   58.0    416  4.24  4.16  2.72
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
27729   2.00  Very Good     F     SI1   57.9   60.0  18759  8.28  8.34  4.81
27733   1.51  Very Good     F    VVS1   62.6   59.0  18777  7.33  7.24  4.56
27736   2.03  Very Good     H     SI1   63.0   60.0  18781  8.00  7.93  5.02
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04

[53940 rows x 10 columns]

In [39]:
df.sort_values(["cut", "price"], ascending=[True, False])

       carat        cut color clarity  depth  table  price      x      y     z
27646   2.01       Fair     G     SI1   70.6   64.0  18574   7.43   6.64  4.69
27643   2.02       Fair     H     VS2   64.5   57.0  18565   8.00   7.95  5.14
27630   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27623   2.00       Fair     G     VS2   67.6   58.0  18515   7.65   7.61  5.16
27543   2.51       Fair     H     SI2   64.7   57.0  18308   8.44   8.50  5.48
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
19      0.30  Very Good     J     SI1   62.7   59.0    351   4.21   4.27  2.66
9       0.23  Very Good     H     VS1   59.4   61.0    338   4.00   4.05  2.39
7       0.26  Very Good     H     SI1   61.9   55.0    337   4.07   4.11  2.53
5       0.24  Very Good     J    VVS2   62.8   57.0    336   3.94   3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336   3.95   3.98  2.47

[53940 rows x 10 columns]

In [40]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [42]:
list(df.cut.unique())

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']

In [43]:
df.cut.nunique()

5

In [44]:
df.shape

(53940, 10)

In [45]:
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [47]:
df.groupby(["cut", "color"])["price"].count()

cut        color
Fair       D         163
           E         224
           F         312
           G         314
           H         303
           I         175
           J         119
Good       D         662
           E         933
           F         909
           G         871
           H         702
           I         522
           J         307
Ideal      D        2834
           E        3903
           F        3826
           G        4884
           H        3115
           I        2093
           J         896
Premium    D        1603
           E        2337
           F        2331
           G        2924
           H        2360
           I        1428
           J         808
Very Good  D        1513
           E        2400
           F        2164
           G        2299
           H        1824
           I        1204
           J         678
Name: price, dtype: int64

In [48]:
df.groupby("cut").price.mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [49]:
df.groupby("cut").price.agg(["min", "max", "mean"])

           min    max         mean
cut
Fair       337  18574  4358.757764
Good       327  18788  3928.864452
Ideal      326  18806  3457.541970
Premium    326  18823  4584.257704
Very Good  336  18818  3981.759891

In [50]:
df.groupby("cut")[["carat", "price"]].agg(["min", "max", "mean"])

          carat                 price
            min   max      mean   min    max         mean
cut
Fair       0.22  5.01  1.046137   337  18574  4358.757764
Good       0.23  3.01  0.849185   327  18788  3928.864452
Ideal      0.20  3.50  0.702837   326  18806  3457.541970
Premium    0.20  4.01  0.891955   326  18823  4584.257704
Very Good  0.20  4.00  0.806381   336  18818  3981.759891

In [53]:
df.groupby("cut").agg({"price": ["min", "max"], "carat": ["median", "mean"]})

          price         carat
            min    max median      mean
cut
Fair        337  18574   1.00  1.046137
Good        327  18788   0.82  0.849185
Ideal       326  18806   0.54  0.702837
Premium     326  18823   0.86  0.891955
Very Good   336  18818   0.71  0.806381

In [56]:
df.pivot_table(index="cut", columns="color", values="price",aggfunc="mean")

color,D,E,F,G,H,I,J
cut,,,,,,,
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274

In [57]:
df.pivot_table(index="cut", columns="color", values="price",aggfunc="count")

color         D     E     F     G     H     I    J
cut
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678

In [62]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [64]:
df["cut"] =  df["cut"].str.upper()

In [65]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      IDEAL     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    PREMIUM     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       GOOD     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    PREMIUM     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       GOOD     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      IDEAL     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       GOOD     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  VERY GOOD     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    PREMIUM     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      IDEAL     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [67]:
# Add 10.000 to the price for Premium cut diamonds
a = df[df.cut == 'PREMIUM']
a['price'] = a['price'] + 10000
a

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  PREMIUM     E     SI1   59.8   61.0  10326  3.89  3.84  2.31
3       0.29  PREMIUM     I     VS2   62.4   58.0  10334  4.20  4.23  2.63
12      0.22  PREMIUM     F     SI1   60.4   61.0  10342  3.88  3.84  2.33
14      0.20  PREMIUM     E     SI2   60.2   62.0  10345  3.79  3.75  2.27
15      0.32  PREMIUM     E      I1   60.9   58.0  10345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  PREMIUM     E     SI2   61.4   58.0  12756  6.03  5.96  3.68
53930   0.71  PREMIUM     E     SI1   60.5   55.0  12756  5.79  5.74  3.49
53931   0.71  PREMIUM     F     SI1   59.8   62.0  12756  5.74  5.73  3.43
53934   0.72  PREMIUM     D     SI1   62.7   59.0  12757  5.69  5.73  3.58
53938   0.86  PREMIUM     H     SI2   61.0   58.0  12757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [68]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      IDEAL     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    PREMIUM     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       GOOD     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    PREMIUM     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       GOOD     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      IDEAL     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       GOOD     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  VERY GOOD     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    PREMIUM     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      IDEAL     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [69]:
a.to_csv("/tmp/diamonds-updated.csv", index=False)

In [70]:
!head /tmp/diamonds-updated.csv

carat,cut,color,clarity,depth,table,price,x,y,z
0.21,PREMIUM,E,SI1,59.8,61.0,10326,3.89,3.84,2.31
0.29,PREMIUM,I,VS2,62.4,58.0,10334,4.2,4.23,2.63
0.22,PREMIUM,F,SI1,60.4,61.0,10342,3.88,3.84,2.33
0.2,PREMIUM,E,SI2,60.2,62.0,10345,3.79,3.75,2.27
0.32,PREMIUM,E,I1,60.9,58.0,10345,4.38,4.42,2.68
0.24,PREMIUM,I,VS1,62.5,57.0,10355,3.97,3.94,2.47
0.29,PREMIUM,F,SI1,62.4,58.0,10403,4.24,4.26,2.65
0.22,PREMIUM,E,VS2,61.6,58.0,10404,3.93,3.89,2.41
0.22,PREMIUM,D,VS2,59.3,62.0,10404,3.91,3.88,2.31

In [73]:
df[df.cut.apply(lambda r: r.endswith('GOOD'))]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.23       GOOD     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.31       GOOD     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5       0.24  VERY GOOD     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  VERY GOOD     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  VERY GOOD     H     SI1   61.9   55.0    337  4.07  4.11  2.53
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53927   0.79       GOOD     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53932   0.70  VERY GOOD     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  VERY GOOD     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53936   0.72       GOOD     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  VERY GOOD     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[16988 rows x 10 columns]

In [75]:
df[df.apply(lambda r: r['cut'].endswith('GOOD'), axis=1)]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.23       GOOD     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.31       GOOD     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5       0.24  VERY GOOD     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  VERY GOOD     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  VERY GOOD     H     SI1   61.9   55.0    337  4.07  4.11  2.53
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53927   0.79       GOOD     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53932   0.70  VERY GOOD     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  VERY GOOD     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53936   0.72       GOOD     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  VERY GOOD     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[16988 rows x 10 columns]

In [76]:
df[df.apply(lambda r: r['cut'].endswith('GOOD') and r['carat']>1.0, axis=1)]

       carat        cut color clarity  depth  table  price     x     y     z
172     1.17  VERY GOOD     J      I1   60.2   61.0   2774  6.83  6.90  4.13
247     1.05  VERY GOOD     J     SI2   63.2   56.0   2789  6.49  6.45  4.09
654     1.01       GOOD     I      I1   63.1   57.0   2844  6.35  6.39  4.02
664     1.01       GOOD     H      I1   64.2   61.0   2846  6.25  6.18  3.99
682     1.20  VERY GOOD     H      I1   63.1   60.0   2850  6.75  6.67  4.23
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
52592   1.03       GOOD     I      I1   57.9   59.0   2540  6.67  6.62  3.85
53649   1.05  VERY GOOD     J      I1   59.6   63.0   2705  6.61  6.55  3.92
53793   1.01  VERY GOOD     I     SI1   63.3   59.0   2730  6.26  6.22  3.95
53875   1.04  VERY GOOD     I      I1   61.6   61.0   2745  6.45  6.47  3.98
53897   1.02       GOOD     H      I1   64.3   63.0   2751  6.28  6.23  4.02

[5460 rows x 10 columns]

In [77]:
df.price

0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64

In [79]:
type(df.price) # series behaves like dict + list

pandas.Series

In [80]:
a = pd.Series(['apple', 'orange', 'banana'])
a

0     apple
1    orange
2    banana
dtype: str

In [81]:
a[0]

'apple'

In [82]:
a[1]

'orange'

In [83]:
a[2]

'banana'

In [84]:
a.index

RangeIndex(start=0, stop=3, step=1)

In [85]:
a = pd.Series(['apple', 'orange', 'banana'], index=[45, 23, 67])
a

45     apple
23    orange
67    banana
dtype: str

In [86]:
a.index

Index([45, 23, 67], dtype='int64')

In [87]:
a[0]

KeyError: 0

In [88]:
a.values[0]

'apple'

In [89]:
a[45]

'apple'

In [91]:
list(a.index)

[45, 23, 67]

In [92]:
list(a.values)

['apple', 'orange', 'banana']

In [98]:
a = pd.Series(['apple', 'orange', 'banana'], index=[45, 23, 67])
a = a.reset_index(drop = True)
#a = a.reset_index()
a

0     apple
1    orange
2    banana
dtype: str

In [101]:
df = pd.DataFrame({"a": [4, 6, 8], "b": ["apple", "orange", "banana"]})
df

   a       b
0  4   apple
1  6  orange
2  8  banana

In [104]:
df = pd.read_csv("/home/aio/training/data/diamonds.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [105]:
df = pd.read_csv("/home/aio/training/data/diamonds.csv", dtype={"depth": "float16", "table": "float16"})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float16
 5   table    53940 non-null  float16
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float16(2), float64(4), int64(1), str(3)
memory usage: 4.0 MB

In [107]:
df1 = pd.DataFrame({"a": [4, 6, 8], "b": ["apple", "orange", "banana"]})
df2 = pd.DataFrame({"a": [4, 6, 8], "b": ["apple", "orange", "banana"]})
pd.concat([df1, df2])

   a       b
0  4   apple
1  6  orange
2  8  banana
0  4   apple
1  6  orange
2  8  banana

In [108]:
from glob import glob

In [112]:
files = glob("/home/aio/training/data/bluebikes/year=2015/*.csv")
dfs = [pd.read_csv(r) for r in files]
df = pd.concat(dfs)
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1474,2015-08-01 00:01:11,2015-08-01 00:25:46,60,Charles Circle - Charles St. at Cambridge St.,42.360835,-71.070840,141,Kendall Street,42.36356,-71.082168,596,Subscriber,\N,0
1,627,2015-08-01 00:01:22,2015-08-01 00:11:49,139,Dana Park,42.361589,-71.107437,19,Buswell St. at Park Dr.,42.347241,-71.105301,127,Subscriber,1975,2
2,630,2015-08-01 00:01:23,2015-08-01 00:11:54,139,Dana Park,42.361589,-71.107437,19,Buswell St. at Park Dr.,42.347241,-71.105301,660,Subscriber,1976,1
3,1413,2015-08-01 00:01:49,2015-08-01 00:25:22,60,Charles Circle - Charles St. at Cambridge St.,42.360835,-71.070840,141,Kendall Street,42.36356,-71.082168,340,Subscriber,\N,0
4,195,2015-08-01 00:01:55,2015-08-01 00:05:11,46,Christian Science Plaza,42.343864,-71.085918,57,Columbus Ave. at Mass. Ave.,42.340799,-71.081572,1297,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149138,466,2015-05-31 23:41:45,2015-05-31 23:49:31,91,One Kendall Square at Hampshire St / Portland St,42.366277,-71.091690,84,CambridgeSide Galleria - CambridgeSide PL at L...,42.366981,-71.076472,277,Subscriber,\N,0
149139,662,2015-05-31 23:42:04,2015-05-31 23:53:07,67,MIT at Mass Ave / Amherst St,42.358100,-71.093198,87,Harvard University Housing - 115 Putnam Ave at...,42.366621,-71.114214,903,Subscriber,1992,2
149140,331,2015-05-31 23:46:31,2015-05-31 23:52:03,43,Rowes Wharf - Atlantic Ave,42.357143,-71.050699,48,Post Office Square,42.356755,-71.055407,617,Subscriber,\N,0
149141,331,2015-05-31 23:46:32,2015-05-31 23:52:03,43,Rowes Wharf - Atlantic Ave,42.357143,-71.050699,48,Post Office Square,42.356755,-71.055407,594,Subscriber,\N,0
149142,309,2015-05-31 23:46:46,2015-05-31 23:51:55,43,Rowes Wharf - Atlantic Ave,42.357143,-71.050699,48,Post Office Square,42.356755,-71.055407,199,Subscriber,\N,0

In [111]:
dfs[0]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1474,2015-08-01 00:01:11,2015-08-01 00:25:46,60,Charles Circle - Charles St. at Cambridge St.,42.360835,-71.070840,141,Kendall Street,42.363560,-71.082168,596,Subscriber,\N,0
1,627,2015-08-01 00:01:22,2015-08-01 00:11:49,139,Dana Park,42.361589,-71.107437,19,Buswell St. at Park Dr.,42.347241,-71.105301,127,Subscriber,1975,2
2,630,2015-08-01 00:01:23,2015-08-01 00:11:54,139,Dana Park,42.361589,-71.107437,19,Buswell St. at Park Dr.,42.347241,-71.105301,660,Subscriber,1976,1
3,1413,2015-08-01 00:01:49,2015-08-01 00:25:22,60,Charles Circle - Charles St. at Cambridge St.,42.360835,-71.070840,141,Kendall Street,42.363560,-71.082168,340,Subscriber,\N,0
4,195,2015-08-01 00:01:55,2015-08-01 00:05:11,46,Christian Science Plaza,42.343864,-71.085918,57,Columbus Ave. at Mass. Ave.,42.340799,-71.081572,1297,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160060,872,2015-08-31 23:50:16,2015-09-01 00:04:49,42,Boylston St. at Arlington St.,42.352033,-71.070627,38,TD Garden - Causeway at Portal Park #2,42.366222,-71.059914,749,Subscriber,\N,0
160061,1990,2015-08-31 23:51:36,2015-09-01 00:24:46,132,Summer St at Cutter St,42.394002,-71.120406,60,Charles Circle - Charles St. at Cambridge St.,42.360835,-71.070840,747,Customer,1986,1
160062,289,2015-08-31 23:51:42,2015-08-31 23:56:32,88,Inman Square at Vellucci Plaza / Hampshire St,42.374035,-71.101427,71,Conway Park - Somerville Avenue,42.383405,-71.107593,1124,Subscriber,1986,1
160063,595,2015-08-31 23:55:49,2015-09-01 00:05:45,67,MIT at Mass Ave / Amherst St,42.358100,-71.093198,9,Agganis Arena - 925 Comm Ave.,42.351246,-71.115639,637,Subscriber,1993,1
160064,695,2015-08-31 23:56:41,2015-09-01 00:08:17,88,Inman Square at Vellucci Plaza / Hampshire St,42.374035,-71.101427,87,Harvard University Housing - 115 Putnam Ave at...,42.366621,-71.114214,717,Subscriber,1988,2

In [113]:
df_iterator = pd.read_csv("/home/aio/training/data/diamonds.csv", chunksize=10000)
for df in df_iterator:
    print(len(df))

10000
10000
10000
10000
10000
3940

In [114]:
#pd.read_parquet()

In [115]:
df

       carat        cut color clarity  depth  table  price     x     y     z
50000   0.57      Ideal     F     VS1   61.0   56.0   2193  5.36  5.40  3.28
50001   0.76       Fair     H     SI1   65.5   59.0   2193  5.75  5.66  3.74
50002   0.74    Premium     I     VS1   62.9   57.0   2193  5.79  5.76  3.63
50003   0.74       Fair     H     VS1   66.3   63.0   2193  5.63  5.50  3.69
50004   0.70    Premium     E     SI1   62.4   60.0   2194  5.72  5.63  3.54
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[3940 rows x 10 columns]

In [117]:
a = df.groupby(["cut", "color"])["price"].agg(["mean","min", "max"])
a

                        mean   min   max
cut       color
Fair      D      2422.263158  2198  2747
          E      2509.263158  2241  2721
          F      2463.730769  2198  2724
          G      2432.042553  2208  2745
          H      2459.629630  2193  2717
          I      2415.333333  2208  2743
          J      2466.000000  2304  2683
Good      D      2123.732143   399  2757
          E      2073.548387   544  2749
          F      2365.641975   399  2756
          G      2248.793103   544  2753
          H      2206.101695   401  2751
          I      2332.733333   552  2753
          J      2444.909091  2195  2729
Ideal     D      2261.587879   541  2757
          E      2402.819549   401  2756
          F      2400.839763   548  2751
          G      2232.481884   542  2756
          H      2158.558824   397  2752
          I      2377.920930   544  2756
          J      2272.685714   400  2742
Premium   D      2252.829787   546  2757
          E      2415.011765   400  2756
          F      2442.125000   550  2756
          G      2277.623457   397  2749
          H      2343.720000   544  2757
          I      2211.469136   544  2753
          J      2289.869565   541  2717
Very Good D      2041.945455   399  2757
          E      2125.514644   400  2757
          F      2140.977477   401  2745
          G      2275.176796   399  2748
          H      2223.148936   399  2739
          I      2290.164062   544  2749
          J      2329.958333   544  2753

In [118]:
a.index

MultiIndex([(     'Fair', 'D'),
            (     'Fair', 'E'),
            (     'Fair', 'F'),
            (     'Fair', 'G'),
            (     'Fair', 'H'),
            (     'Fair', 'I'),
            (     'Fair', 'J'),
            (     'Good', 'D'),
            (     'Good', 'E'),
            (     'Good', 'F'),
            (     'Good', 'G'),
            (     'Good', 'H'),
            (     'Good', 'I'),
            (     'Good', 'J'),
            (    'Ideal', 'D'),
            (    'Ideal', 'E'),
            (    'Ideal', 'F'),
            (    'Ideal', 'G'),
            (    'Ideal', 'H'),
            (    'Ideal', 'I'),
            (    'Ideal', 'J'),
            (  'Premium', 'D'),
            (  'Premium', 'E'),
            (  'Premium', 'F'),
            (  'Premium', 'G'),
            (  'Premium', 'H'),
            (  'Premium', 'I'),
            (  'Premium', 'J'),
            ('Very Good', 'D'),
            ('Very Good', 'E'),
            ('Very Good', 'F'),
            ('Very Good', 'G'),
            ('Very Good', 'H'),
            ('Very Good', 'I'),
            ('Very Good', 'J')],
           names=['cut', 'color'])

In [123]:
a.loc["Fair"]

              mean   min   max
color
D      2422.263158  2198  2747
E      2509.263158  2241  2721
F      2463.730769  2198  2724
G      2432.042553  2208  2745
H      2459.629630  2193  2717
I      2415.333333  2208  2743
J      2466.000000  2304  2683

In [124]:
a.loc["Fair"].loc["D"]

mean    2422.263158
min     2198.000000
max     2747.000000
Name: D, dtype: float64

In [125]:
a.loc["Fair"].loc["D"]["mean"]

np.float64(2422.2631578947367)

In [126]:
# DataFrame 1: Customer Information 

customers_df = pd.DataFrame({ 'customer_id': [1, 2, 3, 4, 5], 
                             'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 
                             'city': ['NY', 'LA', 'Chicago', 'NY', 'SF'] }) 

customers_df

   customer_id     name     city
0            1    Alice       NY
1            2      Bob       LA
2            3  Charlie  Chicago
3            4    David       NY
4            5      Eve       SF

In [128]:
# DataFrame 2: Order Information 
# customer_id 6 is not in customers_df

orders_df = pd.DataFrame({'order_id': [101, 102, 103, 104, 105, 106], 
                          'customer_id': [1, 3, 2, 6, 1, 3], 
                          'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Charger', 'Webcam'], 
                          'amount': [1200, 25, 75, 300, 50, 40] }) 


orders_df

   order_id  customer_id   product  amount
0       101            1    Laptop    1200
1       102            3     Mouse      25
2       103            2  Keyboard      75
3       104            6   Monitor     300
4       105            1   Charger      50
5       106            3    Webcam      40

In [129]:

products_df = pd.DataFrame({ 'prod_id': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Charger', 'Webcam'], 
                            'price_usd': [1200, 25, 75, 300, 50, 40] 
                           })
products_df

    prod_id  price_usd
0    Laptop       1200
1     Mouse         25
2  Keyboard         75
3   Monitor        300
4   Charger         50
5    Webcam         40

In [130]:
pd.merge(customers_df, orders_df, on='customer_id', how='inner')

   customer_id     name     city  order_id   product  amount
0            1    Alice       NY       101    Laptop    1200
1            3  Charlie  Chicago       102     Mouse      25
2            1    Alice       NY       105   Charger      50
3            3  Charlie  Chicago       106    Webcam      40
4            2      Bob       LA       103  Keyboard      75

In [131]:
pd.merge(customers_df, orders_df, left_on='customer_id', right_on="customer_id",  how='inner')

   customer_id     name     city  order_id   product  amount
0            1    Alice       NY       101    Laptop    1200
1            3  Charlie  Chicago       102     Mouse      25
2            1    Alice       NY       105   Charger      50
3            3  Charlie  Chicago       106    Webcam      40
4            2      Bob       LA       103  Keyboard      75

In [133]:
df = pd.DataFrame({"a": [4, 6, 8], "b": ["apple", "orange", "banana"]})
df.columns = ["units", "name"]
df

   units    name
0      4   apple
1      6  orange
2      8  banana

In [136]:
import numpy as np

In [138]:
data = {
    'Category': ['Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Food', 'Food', 'Clothing', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'South', 'North', 'West', 'East', 'North', 'South'],
    'Sales': [100, 150, 200, 120, 90, 180, 50, 70, 110, 130],
    'Quantity': [10, 15, 20, 12, 9, 18, 5, 7, 11, 13],
    'Rating': [4.5, 3.8, 4.2, 4.0, 3.5, 4.7, 3.0, 4.1, np.nan, 3.9] # Added a NaN
}
df = pd.DataFrame(data)

df

      Category Region  Sales  Quantity  Rating
0  Electronics  North    100        10     4.5
1  Electronics  South    150        15     3.8
2     Clothing  North    200        20     4.2
3  Electronics   East    120        12     4.0
4     Clothing  South     90         9     3.5
5  Electronics  North    180        18     4.7
6         Food   West     50         5     3.0
7         Food   East     70         7     4.1
8     Clothing  North    110        11     NaN
9  Electronics  South    130        13     3.9

In [139]:
df.groupby('Category')['Sales'].transform('mean')

0    136.000000
1    136.000000
2    133.333333
3    136.000000
4    133.333333
5    136.000000
6     60.000000
7     60.000000
8    133.333333
9    136.000000
Name: Sales, dtype: float64

In [140]:
df['Avg_Category_Sales'] = df.groupby('Category')['Sales'].transform('mean')
df

      Category Region  Sales  Quantity  Rating  Avg_Category_Sales
0  Electronics  North    100        10     4.5          136.000000
1  Electronics  South    150        15     3.8          136.000000
2     Clothing  North    200        20     4.2          133.333333
3  Electronics   East    120        12     4.0          136.000000
4     Clothing  South     90         9     3.5          133.333333
5  Electronics  North    180        18     4.7          136.000000
6         Food   West     50         5     3.0           60.000000
7         Food   East     70         7     4.1           60.000000
8     Clothing  North    110        11     NaN          133.333333
9  Electronics  South    130        13     3.9          136.000000

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({"a": [1, 2, 3], "b": ["action|thriller", "action", "action|romance"]})
df

   a                b
0  1  action|thriller
1  2           action
2  3   action|romance

In [4]:
df["b"] = df["b"].str.split("|")

In [5]:
df

   a                   b
0  1  [action, thriller]
1  2            [action]
2  3   [action, romance]

In [6]:
df.explode("b")

   a         b
0  1    action
0  1  thriller
1  2    action
2  3    action
2  3   romance