In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "a": [1, 2, 3],
    "b": [4234, 3423, 23]
})
df

   a     b
0  1  4234
1  2  3423
2  3    23

In [3]:
df = pd.read_csv('/home/aio/training/data/diamonds.csv')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
type(df)

pandas.DataFrame

In [5]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [7]:
pd.__version__

'3.0.5'

In [8]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [9]:
df.tail()

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [10]:
df.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53930   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [11]:
df[['carat', 'price']]

       carat  price
0       0.23    326
1       0.21    326
2       0.23    327
3       0.29    334
4       0.31    335
...      ...    ...
53935   0.72   2757
53936   0.72   2757
53937   0.70   2757
53938   0.86   2757
53939   0.75   2757

[53940 rows x 2 columns]

In [12]:
# https://rpubs.com/Davo2812/1102821
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [13]:
df.iloc[100:110]

     carat        cut color clarity  depth  table  price     x     y     z
100   0.75  Very Good     D     SI1   63.2   56.0   2760  5.80  5.75  3.65
101   0.75    Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
102   0.74      Ideal     G     SI1   61.6   55.0   2760  5.80  5.85  3.59
103   0.75    Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
104   0.80      Ideal     I     VS1   62.9   56.0   2760  5.94  5.87  3.72
105   0.75      Ideal     G     SI1   62.2   55.0   2760  5.87  5.80  3.63
106   0.80    Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
107   0.74      Ideal     I    VVS2   62.3   55.0   2761  5.77  5.81  3.61
108   0.81      Ideal     F     SI2   58.8   57.0   2761  6.14  6.11  3.60
109   0.59      Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35

In [14]:
df.index

RangeIndex(start=0, stop=53940, step=1)

In [24]:
df.sample(10)

       carat        cut color clarity  depth  table  price     x     y     z
1464    0.70      Ideal     E     VS2   62.2   55.0   2981  5.67  5.71  3.54
35566   0.35      Ideal     F     VS2   61.4   54.0    906  4.58  4.54  2.80
36088   0.44    Premium     I    VVS1   61.5   58.0    926  4.87  4.95  3.02
7935    1.08  Very Good     G     SI2   63.2   57.0   4318  6.54  6.50  4.12
28711   0.23    Premium     E    VVS2   61.8   58.0    680  3.94  3.92  2.43
35120   0.53    Premium     F      I1   61.3   58.0    886  5.22  5.18  3.19
29764   0.35    Premium     H     VS2   61.8   56.0    709  4.58  4.54  2.82
38652   0.42      Ideal     D     SI1   61.5   56.0   1040  4.85  4.81  2.97
2110    0.85      Ideal     G     SI1   60.4   56.0   3118  6.26  6.17  3.75
9082    1.03    Premium     E     SI2   61.0   60.0   4522  6.53  6.46  3.96

In [36]:
df.sample(frac=0.001)

       carat        cut color clarity  depth  table  price     x     y     z
7819    1.00  Very Good     G     SI1   63.1   56.0   4295  6.41  6.31  4.01
42724   0.60    Premium     H     SI1   58.9   61.0   1341  5.54  5.50  3.25
6846    1.08    Premium     G     SI2   63.0   54.0   4124  6.58  6.54  4.13
41013   0.44      Ideal     H      IF   61.5   56.0   1185  4.89  4.93  3.02
45102   0.60      Ideal     H     VS2   61.1   56.0   1648  5.47  5.49  3.35
36929   0.41      Ideal     G     VS1   61.5   56.0    961  4.79  4.77  2.94
1725    0.32    Premium     G     VS2   61.9   58.0    561  4.36  4.43  2.72
19412   1.22    Premium     G     VS2   60.9   57.0   8067  6.94  6.89  4.21
28544   0.30    Premium     H     VS1   61.4   59.0    675  4.33  4.30  2.65
49396   0.50      Ideal     G      IF   61.5   56.0   2104  5.11  5.14  3.15
25321   1.67      Ideal     H     VS1   61.8   56.0  14014  7.60  7.57  4.69
22711   1.53    Premium     I     VS1   62.4   59.0  10729  7.30  7.34  4.57
22881   1.29      Ideal     F     VS1   62.3   54.0  10923  7.00  6.93  4.34
40808   0.51  Very Good     H     SI1   62.0   57.0   1170  5.11  5.19  3.19
17922   1.39    Premium     J     VS1   60.8   58.0   7239  7.26  7.21  4.40
45858   0.70  Very Good     G     SI2   63.2   57.0   1715  5.66  5.59  3.55
31112   0.30  Very Good     D    VVS2   63.0   56.0    754  4.29  4.31  2.71
26624   2.14    Premium     H     VS2   61.7   58.0  16390  8.28  8.22  5.09
41140   0.50  Very Good     G     SI1   62.9   59.0   1197  5.06  5.09  3.19
17495   1.01    Premium     D     VS2   60.4   58.0   7032  6.57  6.47  3.94
45615   0.50  Very Good     F     VS1   62.0   58.0   1692  5.08  5.11  3.16
52908   0.64      Ideal     G    VVS2   61.8   56.0   2587  5.53  5.56  3.43
41794   0.52    Premium     G     SI1   60.6   61.0   1249  5.19  5.17  3.14
11313   1.15    Premium     G     SI2   62.2   60.0   4985  6.69  6.66  4.15
46212   0.51      Ideal     F     VS1   61.8   55.0   1751  5.13  5.16  3.18
11029   1.23    Premium     G     SI2   62.1   58.0   4918  6.85  6.80  4.24
23241   1.71       Good     I     VS2   58.0   60.0  11250  7.85  7.90  4.57
38842   0.33  Very Good     D    VVS2   60.8   58.0   1050  4.47  4.48  2.72
16167   1.02       Good     E     VS2   63.2   60.0   6462  6.29  6.34  3.99
24330   2.02      Ideal     J     SI1   62.4   56.0  12591  8.03  8.19  5.06
10792   1.07       Good     G     SI1   63.1   59.0   4861  6.45  6.49  4.08
13462   1.00  Very Good     F     SI1   63.3   58.0   5528  6.28  6.39  4.01
15529   1.12      Ideal     H     VS2   61.8   55.0   6222  6.70  6.64  4.12
11367   1.00      Ideal     G     SI1   61.9   56.0   4997  6.37  6.45  3.97
36176   0.30  Very Good     E      IF   62.8   54.0    930  4.30  4.33  2.71
40493   0.42      Ideal     F    VVS2   61.3   57.0   1142  4.80  4.82  2.95
39815   0.40      Ideal     G    VVS1   61.7   57.0   1097  4.71  4.74  2.91
14148   1.25    Premium     H     SI2   61.2   62.0   5740  6.95  6.84  4.22
50028   0.51      Ideal     F    VVS2   61.7   56.0   2197  5.11  5.13  3.16
52964   0.24  Very Good     F      IF   60.0   57.0    552  4.07  4.10  2.45
41916   0.52  Very Good     I     VS1   61.5   56.3   1262  5.16  5.19  3.18
26771   2.06  Very Good     F     SI2   61.5   56.0  16603  8.15  8.18  5.02
49820   0.61      Ideal     G     VS1   60.9   57.0   2167  5.46  5.50  3.34
46045   0.52      Ideal     H     SI1   62.0   55.0   1730  5.16  5.20  3.21
46630   0.30      Ideal     H     VS1   62.7   55.0    526  4.25  4.30  2.68
3175    0.81      Ideal     E     SI1   61.3   57.0   3338  6.08  6.03  3.71
31528   0.34      Ideal     E     SI1   61.8   56.0    765  4.48  4.45  2.76
45064   0.57       Good     F     VS2   62.8   62.0   1642  5.22  5.25  3.29
25768   2.43    Premium     I     SI2   62.2   60.0  14727  8.59  8.53  5.33
16582   1.01  Very Good     E     VS2   59.9   57.0   6622  6.52  6.57  3.92
33188   0.34  Very Good     E    VVS2   61.6   58.0    819  4.50  4.53  2.78
10542   1.01      Ideal     I     VS1   62.6   56.0   4808  6.42  6.36  4.00
46575   1.00       Fair     J      I1   65.0   59.0   1784  6.27  6.17  4.05
1760    0.78  Very Good     F     SI1   62.4   58.0   3045  5.83  5.86  3.65

In [38]:
df[df.cut == 'Ideal']

       carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
11      0.23  Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
13      0.31  Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
16      0.30  Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
39      0.33  Ideal     I     SI2   61.8   55.0    403  4.49  4.51  2.78
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
53925   0.79  Ideal     I     SI1   61.6   56.0   2756  5.95  5.97  3.67
53926   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54
53929   0.71  Ideal     G     VS1   61.4   56.0   2756  5.76  5.73  3.53
53935   0.72  Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53939   0.75  Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[21551 rows x 10 columns]

In [39]:
df[df['cut'] == 'Ideal']

       carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
11      0.23  Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
13      0.31  Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
16      0.30  Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
39      0.33  Ideal     I     SI2   61.8   55.0    403  4.49  4.51  2.78
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
53925   0.79  Ideal     I     SI1   61.6   56.0   2756  5.95  5.97  3.67
53926   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54
53929   0.71  Ideal     G     VS1   61.4   56.0   2756  5.76  5.73  3.53
53935   0.72  Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53939   0.75  Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[21551 rows x 10 columns]

In [40]:
df[(df['cut'] == 'Premium') & (df.price>2000)]

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [42]:
df.query("cut =='Premium' and price>2000")

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [45]:
df.shape

(53940, 10)

In [46]:
df.cut.unique()

<ArrowStringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [47]:
df.cut.nunique()

5

In [49]:
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [50]:
df.groupby('cut').price.mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [52]:
df.groupby('cut').price.agg(['min', 'max'])

           min    max
cut
Fair       337  18574
Good       327  18788
Ideal      326  18806
Premium    326  18823
Very Good  336  18818

In [53]:
df.groupby('cut')[['price', 'carat']].agg(['min', 'max'])

          price        carat
            min    max   min   max
cut
Fair        337  18574  0.22  5.01
Good        327  18788  0.23  3.01
Ideal       326  18806  0.20  3.50
Premium     326  18823  0.20  4.01
Very Good   336  18818  0.20  4.00

In [55]:
a = df.groupby('cut').agg({'price': ['min', 'max'], 'carat': ['mean', 'median']})
a

          price            carat
            min    max      mean median
cut
Fair        337  18574  1.046137   1.00
Good        327  18788  0.849185   0.82
Ideal       326  18806  0.702837   0.54
Premium     326  18823  0.891955   0.86
Very Good   336  18818  0.806381   0.71

In [57]:
a['price']['max']

cut
Fair         18574
Good         18788
Ideal        18806
Premium      18823
Very Good    18818
Name: max, dtype: int64

In [58]:
a['price']['max']['Fair']

np.int64(18574)

In [61]:
df.pivot_table(index='color', columns='cut', values='price', aggfunc='mean')

cut           Fair         Good        Ideal      Premium    Very Good
color
D      4291.061350  3405.382175  2629.094566  3631.292576  3470.467284
E      3682.312500  3423.644159  2597.550090  3538.914420  3214.652083
F      3827.003205  3495.750275  3374.939362  4324.890176  3778.820240
G      4239.254777  4123.482204  3720.706388  4500.742134  3872.753806
H      5135.683168  4276.254986  3889.334831  5216.706780  4535.390351
I      4685.445714  5078.532567  4451.970377  5946.180672  5255.879568
J      4975.655462  4574.172638  4918.186384  6294.591584  5103.513274

In [62]:
data = {
    'A': [1, 2, 1, 3, 2, 4],
    'B': ['apple', 'banana', 'apple', 'orange', 'banana', 'grape'],
    'C': [10, 20, 10, 30, 25, 40]
}
df = pd.DataFrame(data)
df

   A       B   C
0  1   apple  10
1  2  banana  20
2  1   apple  10
3  3  orange  30
4  2  banana  25
5  4   grape  40

In [64]:
df.drop_duplicates(['B'], keep="first")

   A       B   C
0  1   apple  10
1  2  banana  20
3  3  orange  30
5  4   grape  40

In [65]:
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Mouse', 'Monitor', 'Laptop', 'Keyboard', 'Mouse'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Peripherals', 'Electronics', 'Electronics', 'Peripherals', 'Peripherals'],
    'Price': [1200.50, 25.00, 75.25, 300.00, 1150.75, 20.00, 320.50, 1300.00, 80.00, 28.50],
    'Stock': [50, 200, 150, 80, 45, 180, 75, 60, 130, 190],
    'Rating': [4.5, 3.8, 4.2, 4.0, 4.7, 3.5, 4.1, None, 4.3, 3.9], # Added a NaN
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South']
}
# Custom index for demonstration
custom_index = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10']
df = pd.DataFrame(data, index=custom_index)
df

      Product     Category    Price  Stock  Rating Region
P1     Laptop  Electronics  1200.50     50     4.5  North
P2      Mouse  Electronics    25.00    200     3.8  South
P3   Keyboard  Electronics    75.25    150     4.2   East
P4    Monitor  Electronics   300.00     80     4.0   West
P5     Laptop  Electronics  1150.75     45     4.7  North
P6      Mouse  Peripherals    20.00    180     3.5  South
P7    Monitor  Electronics   320.50     75     4.1   East
P8     Laptop  Electronics  1300.00     60     NaN   West
P9   Keyboard  Peripherals    80.00    130     4.3  North
P10     Mouse  Peripherals    28.50    190     3.9  South

In [66]:
df.loc[df['Region'] == 'East', 'Price'] = 999.99
df

      Product     Category    Price  Stock  Rating Region
P1     Laptop  Electronics  1200.50     50     4.5  North
P2      Mouse  Electronics    25.00    200     3.8  South
P3   Keyboard  Electronics   999.99    150     4.2   East
P4    Monitor  Electronics   300.00     80     4.0   West
P5     Laptop  Electronics  1150.75     45     4.7  North
P6      Mouse  Peripherals    20.00    180     3.5  South
P7    Monitor  Electronics   999.99     75     4.1   East
P8     Laptop  Electronics  1300.00     60     NaN   West
P9   Keyboard  Peripherals    80.00    130     4.3  North
P10     Mouse  Peripherals    28.50    190     3.9  South

In [67]:
df

      Product     Category    Price  Stock  Rating Region
P1     Laptop  Electronics  1200.50     50     4.5  North
P2      Mouse  Electronics    25.00    200     3.8  South
P3   Keyboard  Electronics   999.99    150     4.2   East
P4    Monitor  Electronics   300.00     80     4.0   West
P5     Laptop  Electronics  1150.75     45     4.7  North
P6      Mouse  Peripherals    20.00    180     3.5  South
P7    Monitor  Electronics   999.99     75     4.1   East
P8     Laptop  Electronics  1300.00     60     NaN   West
P9   Keyboard  Peripherals    80.00    130     4.3  North
P10     Mouse  Peripherals    28.50    190     3.9  South

In [68]:
# Custom function: Range (max - min)
def data_range(series):
    return series.max() - series.min()

df.groupby('Product')['Price'].agg(data_range)

Product
Keyboard    919.99
Laptop      149.25
Monitor     699.99
Mouse         8.50
Name: Price, dtype: float64

In [69]:
# DataFrame 1: Customer Information 

customers_df = pd.DataFrame({ 'customer_id': [1, 2, 3, 4, 5], 
                             'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 
                             'city': ['NY', 'LA', 'Chicago', 'NY', 'SF'] }) 

# DataFrame 2: Order Information 
# customer_id 6 is not in customers_df

orders_df = pd.DataFrame({'order_id': [101, 102, 103, 104, 105, 106], 
                          'customer_id': [1, 3, 2, 6, 1, 3], 
                          'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Charger', 'Webcam'], 
                          'amount': [1200, 25, 75, 300, 50, 40] }) 


products_df = pd.DataFrame({ 'prod_id': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Charger', 'Webcam'], 
                            'price_usd': [1200, 25, 75, 300, 50, 40] 
                           })

In [71]:
customers_df

   customer_id     name     city
0            1    Alice       NY
1            2      Bob       LA
2            3  Charlie  Chicago
3            4    David       NY
4            5      Eve       SF

In [72]:
products_df

    prod_id  price_usd
0    Laptop       1200
1     Mouse         25
2  Keyboard         75
3   Monitor        300
4   Charger         50
5    Webcam         40

In [73]:
orders_df

   order_id  customer_id   product  amount
0       101            1    Laptop    1200
1       102            3     Mouse      25
2       103            2  Keyboard      75
3       104            6   Monitor     300
4       105            1   Charger      50
5       106            3    Webcam      40

In [75]:
orders_df.merge(products_df, left_on='product', right_on='prod_id', how='inner')

   order_id  customer_id   product  amount   prod_id  price_usd
0       101            1    Laptop    1200    Laptop       1200
1       102            3     Mouse      25     Mouse         25
2       103            2  Keyboard      75  Keyboard         75
3       104            6   Monitor     300   Monitor        300
4       105            1   Charger      50   Charger         50
5       106            3    Webcam      40    Webcam         40

In [76]:
# Create first DataFrame
df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

# Create second DataFrame
df2 = pd.DataFrame({
    'id': [4, 5],
    'name': ['David', 'Eva']
})

# Concatenate row-wise (stacking one below the other)
df_combined = pd.concat([df1, df2], ignore_index=True)

In [77]:
df1

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

In [78]:
df2

   id   name
0   4  David
1   5    Eva

In [79]:
df_combined

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva

In [81]:
import numpy as np

In [82]:
data = {
    'Category': ['Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Food', 'Food', 'Clothing', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'South', 'North', 'West', 'East', 'North', 'South'],
    'Sales': [100, 150, 200, 120, 90, 180, 50, 70, 110, 130],
    'Quantity': [10, 15, 20, 12, 9, 18, 5, 7, 11, 13],
    'Rating': [4.5, 3.8, 4.2, 4.0, 3.5, 4.7, 3.0, 4.1, np.nan, 3.9] # Added a NaN
}
df = pd.DataFrame(data)
df

      Category Region  Sales  Quantity  Rating
0  Electronics  North    100        10     4.5
1  Electronics  South    150        15     3.8
2     Clothing  North    200        20     4.2
3  Electronics   East    120        12     4.0
4     Clothing  South     90         9     3.5
5  Electronics  North    180        18     4.7
6         Food   West     50         5     3.0
7         Food   East     70         7     4.1
8     Clothing  North    110        11     NaN
9  Electronics  South    130        13     3.9

In [83]:
df['Avg_Category_Sales'] = df.groupby('Category')['Sales'].transform('mean')

In [84]:
df

      Category Region  Sales  Quantity  Rating  Avg_Category_Sales
0  Electronics  North    100        10     4.5          136.000000
1  Electronics  South    150        15     3.8          136.000000
2     Clothing  North    200        20     4.2          133.333333
3  Electronics   East    120        12     4.0          136.000000
4     Clothing  South     90         9     3.5          133.333333
5  Electronics  North    180        18     4.7          136.000000
6         Food   West     50         5     3.0           60.000000
7         Food   East     70         7     4.1           60.000000
8     Clothing  North    110        11     NaN          133.333333
9  Electronics  South    130        13     3.9          136.000000

In [85]:
df['Cumulative_Sales_Region'] = df.groupby('Region')['Sales'].cumsum()
df

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region
0,Electronics,North,100,10,4.5,136.000000,100
1,Electronics,South,150,15,3.8,136.000000,150
2,Clothing,North,200,20,4.2,133.333333,300
3,Electronics,East,120,12,4.0,136.000000,120
4,Clothing,South,90,9,3.5,133.333333,240
5,Electronics,North,180,18,4.7,136.000000,480
6,Food,West,50,5,3.0,60.000000,50
7,Food,East,70,7,4.1,60.000000,190
8,Clothing,North,110,11,NaN,133.333333,590
9,Electronics,South,130,13,3.9,136.000000,370

In [86]:
df['Sales_Rank_in_Category'] = df.groupby('Category')['Sales'].rank(method='min', ascending=False)
df

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region,Sales_Rank_in_Category
0,Electronics,North,100,10,4.5,136.000000,100,5.0
1,Electronics,South,150,15,3.8,136.000000,150,2.0
2,Clothing,North,200,20,4.2,133.333333,300,1.0
3,Electronics,East,120,12,4.0,136.000000,120,4.0
4,Clothing,South,90,9,3.5,133.333333,240,3.0
5,Electronics,North,180,18,4.7,136.000000,480,1.0
6,Food,West,50,5,3.0,60.000000,50,2.0
7,Food,East,70,7,4.1,60.000000,190,1.0
8,Clothing,North,110,11,NaN,133.333333,590,2.0
9,Electronics,South,130,13,3.9,136.000000,370,3.0

In [87]:
import duckdb

In [89]:
duckdb.sql('select * from df')

┌─────────────┬─────────┬───────┬──────────┬────────┬────────────────────┬─────────────────────────┬────────────────────────┐
│  Category   │ Region  │ Sales │ Quantity │ Rating │ Avg_Category_Sales │ Cumulative_Sales_Region │ Sales_Rank_in_Category │
│   varchar   │ varchar │ int64 │  int64   │ double │       double       │          int64          │         double         │
├─────────────┼─────────┼───────┼──────────┼────────┼────────────────────┼─────────────────────────┼────────────────────────┤
│ Electronics │ North   │   100 │       10 │    4.5 │              136.0 │                     100 │                    5.0 │
│ Electronics │ South   │   150 │       15 │    3.8 │              136.0 │                     150 │                    2.0 │
│ Clothing    │ North   │   200 │       20 │    4.2 │ 133.33333333333334 │                     300 │                    1.0 │
│ Electronics │ East    │   120 │       12 │    4.0 │              136.0 │                     120 │                    4.0 │
│ Clothing    │ South   │    90 │        9 │    3.5 │ 133.33333333333334 │                     240 │                    3.0 │
│ Electronics │ North   │   180 │       18 │    4.7 │              136.0 │                     480 │                    1.0 │
│ Food        │ West    │    50 │        5 │    3.0 │               60.0 │                      50 │                    2.0 │
│ Food        │ East    │    70 │        7 │    4.1 │               60.0 │                     190 │                    1.0 │
│ Clothing    │ North   │   110 │       11 │   NULL │ 133.33333333333334 │                     590 │                    2.0 │
│ Electronics │ South   │   130 │       13 │    3.9 │              136.0 │                     370 │                    3.0 │
└─────────────┴─────────┴───────┴──────────┴────────┴────────────────────┴─────────────────────────┴────────────────────────┘
  10 rows                                                                                                         8 columns

In [94]:
a = duckdb.sql('''select 
* ,
rank() over(partition by Region order by Sales desc) Sales_Rank_in_Category
from df
''')
a

┌─────────────┬─────────┬───────┬──────────┬────────┬────────────────────┬─────────────────────────┬────────────────────────┬──────────────────────────┐
│  Category   │ Region  │ Sales │ Quantity │ Rating │ Avg_Category_Sales │ Cumulative_Sales_Region │ Sales_Rank_in_Category │ Sales_Rank_in_Category_1 │
│   varchar   │ varchar │ int64 │  int64   │ double │       double       │          int64          │         double         │          int64           │
├─────────────┼─────────┼───────┼──────────┼────────┼────────────────────┼─────────────────────────┼────────────────────────┼──────────────────────────┤
│ Electronics │ South   │   150 │       15 │    3.8 │              136.0 │                     150 │                    2.0 │                        1 │
│ Electronics │ South   │   130 │       13 │    3.9 │              136.0 │                     370 │                    3.0 │                        2 │
│ Clothing    │ South   │    90 │        9 │    3.5 │ 133.33333333333334 │                     240 │                    3.0 │                        3 │
│ Food        │ West    │    50 │        5 │    3.0 │               60.0 │                      50 │                    2.0 │                        1 │
│ Electronics │ East    │   120 │       12 │    4.0 │              136.0 │                     120 │                    4.0 │                        1 │
│ Food        │ East    │    70 │        7 │    4.1 │               60.0 │                     190 │                    1.0 │                        2 │
│ Clothing    │ North   │   200 │       20 │    4.2 │ 133.33333333333334 │                     300 │                    1.0 │                        1 │
│ Electronics │ North   │   180 │       18 │    4.7 │              136.0 │                     480 │                    1.0 │                        2 │
│ Clothing    │ North   │   110 │       11 │   NULL │ 133.33333333333334 │                     590 │                    2.0 │                        3 │
│ Electronics │ North   │   100 │       10 │    4.5 │              136.0 │                     100 │                    5.0 │                        4 │
└─────────────┴─────────┴───────┴──────────┴────────┴────────────────────┴─────────────────────────┴────────────────────────┴──────────────────────────┘
  10 rows                                                                                                                                    9 columns

In [96]:
a.to_df()

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region,Sales_Rank_in_Category,Sales_Rank_in_Category_1
0,Food,West,50,5,3.0,60.000000,50,2.0,1
1,Electronics,South,150,15,3.8,136.000000,150,2.0,1
2,Electronics,South,130,13,3.9,136.000000,370,3.0,2
3,Clothing,South,90,9,3.5,133.333333,240,3.0,3
4,Electronics,East,120,12,4.0,136.000000,120,4.0,1
5,Food,East,70,7,4.1,60.000000,190,1.0,2
6,Clothing,North,200,20,4.2,133.333333,300,1.0,1
7,Electronics,North,180,18,4.7,136.000000,480,1.0,2
8,Clothing,North,110,11,NaN,133.333333,590,2.0,3
9,Electronics,North,100,10,4.5,136.000000,100,5.0,4

In [97]:
df

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region,Sales_Rank_in_Category
0,Electronics,North,100,10,4.5,136.000000,100,5.0
1,Electronics,South,150,15,3.8,136.000000,150,2.0
2,Clothing,North,200,20,4.2,133.333333,300,1.0
3,Electronics,East,120,12,4.0,136.000000,120,4.0
4,Clothing,South,90,9,3.5,133.333333,240,3.0
5,Electronics,North,180,18,4.7,136.000000,480,1.0
6,Food,West,50,5,3.0,60.000000,50,2.0
7,Food,East,70,7,4.1,60.000000,190,1.0
8,Clothing,North,110,11,NaN,133.333333,590,2.0
9,Electronics,South,130,13,3.9,136.000000,370,3.0

In [98]:
df.Region.apply(lambda r: r.upper())

0    NORTH
1    SOUTH
2    NORTH
3     EAST
4    SOUTH
5    NORTH
6     WEST
7     EAST
8    NORTH
9    SOUTH
Name: Region, dtype: str

In [100]:
df.Region.str.upper()

0    NORTH
1    SOUTH
2    NORTH
3     EAST
4    SOUTH
5    NORTH
6     WEST
7     EAST
8    NORTH
9    SOUTH
Name: Region, dtype: str

In [101]:
df['Region'] = df.Region.str.upper()
df

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region,Sales_Rank_in_Category
0,Electronics,NORTH,100,10,4.5,136.000000,100,5.0
1,Electronics,SOUTH,150,15,3.8,136.000000,150,2.0
2,Clothing,NORTH,200,20,4.2,133.333333,300,1.0
3,Electronics,EAST,120,12,4.0,136.000000,120,4.0
4,Clothing,SOUTH,90,9,3.5,133.333333,240,3.0
5,Electronics,NORTH,180,18,4.7,136.000000,480,1.0
6,Food,WEST,50,5,3.0,60.000000,50,2.0
7,Food,EAST,70,7,4.1,60.000000,190,1.0
8,Clothing,NORTH,110,11,NaN,133.333333,590,2.0
9,Electronics,SOUTH,130,13,3.9,136.000000,370,3.0

In [103]:
df.apply(lambda r: r.Sales, axis = 1)

0    100
1    150
2    200
3    120
4     90
5    180
6     50
7     70
8    110
9    130
dtype: int64

In [104]:
df.apply(lambda r: r.Sales/r.Quantity, axis = 1)

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5    10.0
6    10.0
7    10.0
8    10.0
9    10.0
dtype: float64

In [105]:
df

,Category,Region,Sales,Quantity,Rating,Avg_Category_Sales,Cumulative_Sales_Region,Sales_Rank_in_Category
0,Electronics,NORTH,100,10,4.5,136.000000,100,5.0
1,Electronics,SOUTH,150,15,3.8,136.000000,150,2.0
2,Clothing,NORTH,200,20,4.2,133.333333,300,1.0
3,Electronics,EAST,120,12,4.0,136.000000,120,4.0
4,Clothing,SOUTH,90,9,3.5,133.333333,240,3.0
5,Electronics,NORTH,180,18,4.7,136.000000,480,1.0
6,Food,WEST,50,5,3.0,60.000000,50,2.0
7,Food,EAST,70,7,4.1,60.000000,190,1.0
8,Clothing,NORTH,110,11,NaN,133.333333,590,2.0
9,Electronics,SOUTH,130,13,3.9,136.000000,370,3.0

In [107]:
df.apply(lambda r: r.min())

Category                   Clothing
Region                         EAST
Sales                            50
Quantity                          5
Rating                          3.0
Avg_Category_Sales             60.0
Cumulative_Sales_Region          50
Sales_Rank_in_Category          1.0
dtype: object