In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "a": [4, 5, 6, 2],
    "b": ["apple", "banana", "cherry", "durian"]
})
df

   a       b
0  4   apple
1  5  banana
2  6  cherry
3  2  durian

In [4]:
df.dtypes

a    int64
b      str
dtype: object

In [5]:
pd.__version__

'3.0.5'

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      str
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [7]:
df["b"] = df["b"].str.upper()
df

   a       b
0  4   APPLE
1  5  BANANA
2  6  CHERRY
3  2  DURIAN

In [10]:
# https://rpubs.com/Davo2812/1102821
df = pd.read_csv("/home/aio/training/data/diamonds.csv")
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [11]:
len(df)

53940

In [12]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [13]:
len(df.columns)

10

In [14]:
df.shape

(53940, 10)

In [15]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [16]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [17]:
df.tail()

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [18]:
df.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53930   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [19]:
df.cut

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: str

In [20]:
df['cut']

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: str

In [21]:
df[['cut', 'price']]

             cut  price
0          Ideal    326
1        Premium    326
2           Good    327
3        Premium    334
4           Good    335
...          ...    ...
53935      Ideal   2757
53936       Good   2757
53937  Very Good   2757
53938    Premium   2757
53939      Ideal   2757

[53940 rows x 2 columns]

In [22]:
df.iloc[100:110]

     carat        cut color clarity  depth  table  price     x     y     z
100   0.75  Very Good     D     SI1   63.2   56.0   2760  5.80  5.75  3.65
101   0.75    Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
102   0.74      Ideal     G     SI1   61.6   55.0   2760  5.80  5.85  3.59
103   0.75    Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
104   0.80      Ideal     I     VS1   62.9   56.0   2760  5.94  5.87  3.72
105   0.75      Ideal     G     SI1   62.2   55.0   2760  5.87  5.80  3.63
106   0.80    Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
107   0.74      Ideal     I    VVS2   62.3   55.0   2761  5.77  5.81  3.61
108   0.81      Ideal     F     SI2   58.8   57.0   2761  6.14  6.11  3.60
109   0.59      Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35

In [23]:
df.iloc[[100,102, 110]]

     carat        cut color clarity  depth  table  price     x     y     z
100   0.75  Very Good     D     SI1   63.2   56.0   2760  5.80  5.75  3.65
102   0.74      Ideal     G     SI1   61.6   55.0   2760  5.80  5.85  3.59
110   0.80      Ideal     F     SI2   61.4   57.0   2761  5.96  6.00  3.67

In [24]:
df[df.cut == 'Premium']

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]

In [25]:
df[(df.cut == 'Premium') & (df.price>2000)]

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [28]:
df.query('cut == "Premium" and price>2000')

       carat      cut color clarity  depth  table  price     x     y     z
99      0.80  Premium     H     SI1   61.5   58.0   2760  5.97  5.93  3.66
101     0.75  Premium     E     SI1   59.9   54.0   2760  6.00  5.96  3.58
103     0.75  Premium     G     VS2   61.7   58.0   2760  5.85  5.79  3.59
106     0.80  Premium     G     SI1   63.0   59.0   2760  5.90  5.81  3.69
112     0.90  Premium     I     VS2   63.0   58.0   2761  6.16  6.12  3.87
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[8393 rows x 10 columns]

In [29]:
df.cut.nunique()

5

In [32]:
df.cut.unique().tolist()

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']

In [33]:
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [34]:
df.groupby("cut").price.mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [35]:
df.groupby("cut").price.agg(["mean", "min", "max"])

                  mean  min    max
cut
Fair       4358.757764  337  18574
Good       3928.864452  327  18788
Ideal      3457.541970  326  18806
Premium    4584.257704  326  18823
Very Good  3981.759891  336  18818

In [36]:
df.groupby("cut")[["carat","price"]].agg(["mean", "min", "max"])

              carat                    price
               mean   min   max         mean  min    max
cut
Fair       1.046137  0.22  5.01  4358.757764  337  18574
Good       0.849185  0.23  3.01  3928.864452  327  18788
Ideal      0.702837  0.20  3.50  3457.541970  326  18806
Premium    0.891955  0.20  4.01  4584.257704  326  18823
Very Good  0.806381  0.20  4.00  3981.759891  336  18818

In [40]:
a = df.groupby("cut").agg({"carat": ["mean", "min", "max"], "price": ["mean", "median"]})
a

              carat                    price
               mean   min   max         mean  median
cut
Fair       1.046137  0.22  5.01  4358.757764  3282.0
Good       0.849185  0.23  3.01  3928.864452  3050.5
Ideal      0.702837  0.20  3.50  3457.541970  1810.0
Premium    0.891955  0.20  4.01  4584.257704  3185.0
Very Good  0.806381  0.20  4.00  3981.759891  2648.0

In [43]:
a["price"]["mean"]["Good"]

np.float64(3928.864451691806)

In [44]:
a.index

Index(['Fair', 'Good', 'Ideal', 'Premium', 'Very Good'], dtype='str', name='cut')

In [45]:
a.columns

MultiIndex([('carat',   'mean'),
            ('carat',    'min'),
            ('carat',    'max'),
            ('price',   'mean'),
            ('price', 'median')],
           )

In [47]:
df.sort_values("cut")

       carat        cut color clarity  depth  table  price     x     y     z
3850    1.01       Fair     F     SI2   64.8   55.0   3477  6.37  6.26  4.10
51464   1.20       Fair     G      I1   66.6   57.0   2376  6.57  6.50  4.34
51466   0.90       Fair     G     SI2   65.4   57.0   2376  6.01  5.97  3.98
10237   1.26       Fair     D     SI2   64.5   59.0   4746  6.75  6.71  4.34
10760   1.01       Fair     E     SI1   69.5   55.0   4853  6.00  5.94  4.15
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
7402    0.33  Very Good     G     VS2   62.8   54.0    579  4.40  4.42  2.77
43101   0.57  Very Good     E     SI2   58.8   57.3   1384  5.42  5.46  3.21
16893   1.00  Very Good     G     VS2   62.2   58.0   6743  6.35  6.39  3.96
16898   1.00  Very Good     D     VS2   59.6   60.0   6745  6.52  6.57  3.90
21164   1.00  Very Good     E    VVS2   61.7   55.0   9324  6.38  6.42  3.95

[53940 rows x 10 columns]

In [48]:
df.sort_values("cut", ascending=False)

       carat        cut color clarity  depth  table  price     x     y     z
8748    1.06  Very Good     H     SI2   61.7   59.5   4465  6.51  6.53  4.02
23064   1.52  Very Good     G     VS2   62.4   56.0  11093  7.26  7.36  4.56
23058   2.20  Very Good     H     SI2   63.3   57.0  11088  8.28  8.17  5.21
31236   0.42  Very Good     D     SI1   60.2   57.0    756  4.85  4.89  2.93
19154   1.51  Very Good     D     SI2   63.2   59.0   7915  7.25  7.18  4.56
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
5595    1.01       Fair     H     SI1   65.3   61.0   3869  6.23  6.18  4.05
5594    1.01       Fair     H     SI1   64.5   59.0   3869  6.27  6.23  4.03
5585    1.00       Fair     F     SI2   65.5   54.0   3864  6.20  6.16  4.05
5576    1.21       Fair     H     SI2   65.6   56.0   3862  6.69  6.59  4.36
21921   1.70       Fair     F     SI2   64.5   57.0   9996  7.55  7.51  4.86

[53940 rows x 10 columns]

In [49]:
df.sort_values(["cut", "price"], ascending=False)

       carat        cut color clarity  depth  table  price     x     y     z
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27736   2.03  Very Good     H     SI1   63.0   60.0  18781  8.00  7.93  5.02
27733   1.51  Very Good     F    VVS1   62.6   59.0  18777  7.33  7.24  4.56
27729   2.00  Very Good     F     SI1   57.9   60.0  18759  8.28  8.34  4.81
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
10030   0.30       Fair     J     VS2   64.8   58.0    416  4.24  4.16  2.72
31615   0.27       Fair     E     VS1   66.4   58.0    371  3.99  4.02  2.66
31611   0.23       Fair     G    VVS2   61.4   66.0    369  3.87  3.91  2.39
28270   0.25       Fair     E     VS1   55.2   64.0    361  4.21  4.23  2.33
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49

[53940 rows x 10 columns]

In [50]:
df.sort_values(["cut", "price"])

       carat        cut color clarity  depth  table  price     x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
28270   0.25       Fair     E     VS1   55.2   64.0    361  4.21  4.23  2.33
31611   0.23       Fair     G    VVS2   61.4   66.0    369  3.87  3.91  2.39
31615   0.27       Fair     E     VS1   66.4   58.0    371  3.99  4.02  2.66
10030   0.30       Fair     J     VS2   64.8   58.0    416  4.24  4.16  2.72
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
27729   2.00  Very Good     F     SI1   57.9   60.0  18759  8.28  8.34  4.81
27733   1.51  Very Good     F    VVS1   62.6   59.0  18777  7.33  7.24  4.56
27736   2.03  Very Good     H     SI1   63.0   60.0  18781  8.00  7.93  5.02
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04

[53940 rows x 10 columns]

In [51]:
df.sort_values(["cut", "price"], ascending=[False, True])

       carat        cut color clarity  depth  table  price      x      y     z
5       0.24  Very Good     J    VVS2   62.8   57.0    336   3.94   3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336   3.95   3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337   4.07   4.11  2.53
9       0.23  Very Good     H     VS1   59.4   61.0    338   4.00   4.05  2.39
19      0.30  Very Good     J     SI1   62.7   59.0    351   4.21   4.27  2.66
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
27543   2.51       Fair     H     SI2   64.7   57.0  18308   8.44   8.50  5.48
27623   2.00       Fair     G     VS2   67.6   58.0  18515   7.65   7.61  5.16
27630   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27643   2.02       Fair     H     VS2   64.5   57.0  18565   8.00   7.95  5.14
27646   2.01       Fair     G     SI1   70.6   64.0  18574   7.43   6.64  4.69

[53940 rows x 10 columns]

In [53]:
df.pivot_table("price", "cut", "color")

color,D,E,F,G,H,I,J
cut,,,,,,,
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274

In [54]:
df.pivot_table("price", "cut", "color", aggfunc="count")

color         D     E     F     G     H     I    J
cut
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678

In [55]:
df.pivot_table("price", "cut", "color", aggfunc="min")

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

In [57]:
df[df.cut.apply(lambda r: "Good" in r)]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53927   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[16988 rows x 10 columns]

In [59]:
df[df.apply(lambda r: "Good" in r['cut'], axis = 1)]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53927   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[16988 rows x 10 columns]

In [60]:
df[df.apply(lambda r: "Good" in r['cut'] and r['price']>2000, axis = 1)]

       carat        cut color clarity  depth  table  price     x     y     z
93      0.71  Very Good     E     VS2   62.4   57.0   2759  5.68  5.73  3.56
94      0.78  Very Good     G     SI2   63.8   56.0   2759  5.81  5.85  3.72
95      0.70       Good     E     VS2   57.5   58.0   2759  5.85  5.90  3.38
96      0.70       Good     F     VS1   59.4   62.0   2759  5.71  5.76  3.40
98      0.73  Very Good     E     SI1   61.6   59.0   2760  5.77  5.78  3.56
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53927   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[10169 rows x 10 columns]

In [63]:
def find_range(a):
    return max(a) - min(a)
df.groupby("cut").price.agg(find_range)

cut
Fair         18237
Good         18461
Ideal        18480
Premium      18497
Very Good    18482
Name: price, dtype: int64